---
title: "Carly Davenport/Erik Van CEE218X Final Project "
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r global, include=FALSE}
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(mapview)
library(leaflet)
library(tidycensus)
library(StatMatch)
library(geojsonsf)
library(geojson)
library(plotly)
library(httr)
library(flexdashboard)
library(shiny)
```


```{r}
usa_zips <- zctas(cb = T, progress_bar = F)
oakland_data <- readRDS("oakland_data.rds")
alameda_data <- readRDS("alameda_data.rds")
covidData_oakland <- readRDS("covidData_oakland.rds")
covidData_oakland_drop_geo <- readRDS("covidData_oakland_drop_geo.rds")
```

Inputs {.sidebar}
-------------------------------------

```{r}
checkboxGroupInput(
 inputId = "target_income",
 label = "income:",
 choices = c("Less than $10,000", "$10,000 to $14,999", "$15,000 to $19,999", "$20,000 to $24,999", "$25,000 to $29,999", "$30,000 to $34,999", "$35,000 to $39,999", "$40,000 to $44,999", "$45,000 to $49,999", "$50,000 to $59,999", "$60,000 to $74,999", "$75,000 to $99,999", "$100,000 to $124,999", "$125,000 to $149,999", "$150,000 to $199,999", "$200,000 or more"),
 selected = "Less than $10,000"
)
selectInput(
  inputId = "target_race", 
  label = "race:",
  choices = c("Native Hawaiian and Other Pacific Islander Alone", "American Indian and Alaska Native Alone", "Black or African American", "Asian Alone", "White Alone", "Some Other Race Alone", "Two or More Races"), 
  selected = "Native Hawaiian and Other Pacific Islander Alone"
)

selectInput(
  inputId = "regression_var1", 
  label = "regression variable 1 (X):",
  choices = c("CaseRates", "TestRates","Less than $10,000", "$10,000 to $14,999", "$15,000 to $19,999", "$20,000 to $24,999", "$25,000 to $29,999", "$30,000 to $34,999", "$35,000 to $39,999", "$40,000 to $44,999", "$45,000 to $49,999", "$50,000 to $59,999", "$60,000 to $74,999", "$75,000 to $99,999", "$100,000 to $124,999", "$125,000 to $149,999", "$150,000 to $199,999", "$200,000 or more","Native Hawaiian and Other Pacific Islander Alone", "American Indian and Alaska Native Alone", "Black or African American", "Asian Alone", "White Alone", "Some Other Race Alone", "Two or More Races"), 
  selected = "TestRates"
  
)

selectInput(
  inputId = "regression_var2", 
  label = "regression variable 2(Y):",
  choices = c("CaseRates", "TestRates"), 
  selected = "CaseRates"
  
)
```


Row
-------------------------------------
### Plotting Race in Oakland

```{r}
leafletOutput("map1")
```

```{r, context = "server"}
observeEvent({
  input$target_income
  input$target_race
  },  {
     
     oakland_target_race_by_zip <- oakland_data %>% 
        select(Zip_Number, estimate, race) %>%
        group_by(Zip_Number, race) %>%
        mutate(Zip_Number = as.numeric(Zip_Number)) %>%
        summarize(estimate = sum(estimate)) %>%
       filter(race %in% input$target_race) %>%
         select(-race) 
      
     oakland_target_race_by_zip_sf <- oakland_target_race_by_zip %>%
       left_join(
         usa_zips %>%
           transmute(GEOID10 = as.numeric(GEOID10)),
         by = c("Zip_Number" = "GEOID10")
         ) %>%
       st_as_sf()
     race_pal <- colorNumeric(
       palette = "Reds",
       domain = oakland_target_race_by_zip_sf$oakland_target_race_by_zip
       )
    output$map1 <- renderLeaflet({
      leaflet() %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addPolygons(
        data = oakland_target_race_by_zip_sf,
        fillColor = ~race_pal(oakland_target_race_by_zip$estimate),
        color = "white",
        weight = 0.5,
        fillOpacity = 0.5,
        label = ~oakland_target_race_by_zip$estimate
        ) %>%
      addLegend(
        data = oakland_target_race_by_zip_sf,
        pal = race_pal,
        values = ~oakland_target_race_by_zip$estimate,
        title = paste0("Oakland Race Breakdown: <br>", input$target_race)
        )
    })
})
```

### Plotting Income in Oakland

```{r}
leafletOutput("map2")
```

```{r, context = "server"}
observeEvent({
  input$target_income
  input$target_race
  },  {
     
     oakland_target_income_by_zip <- oakland_data %>% 
       select(Zip_Number, estimate, income) %>%
       group_by(Zip_Number, income) %>%
       mutate(Zip_Number = as.numeric(Zip_Number)) %>%
       summarize(estimate = sum(estimate)) %>%
      filter(income %in% input$target_income) %>%
        select(-income) 
      
      oakland_target_income_by_zip_sf <- oakland_target_income_by_zip %>% 
      left_join(
        usa_zips %>%
          transmute(GEOID10 = as.numeric(GEOID10)),
        by = c("Zip_Number" = "GEOID10")
        ) %>%
      st_as_sf()
    income_pal <- colorNumeric(
      palette = "Reds",
      domain = oakland_target_income_by_zip_sf$oakland_target_income_by_zip
      )
    output$map2 <- renderLeaflet({
      leaflet() %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addPolygons(
        data = oakland_target_income_by_zip_sf,
        fillColor = ~income_pal(oakland_target_income_by_zip$estimate),
        color = "white",
        weight = 0.5,
        fillOpacity = 0.5,
        label = ~oakland_target_income_by_zip$estimate
        ) %>%
      addLegend(
        data = oakland_target_income_by_zip_sf,
        pal = income_pal,
        values = ~oakland_target_income_by_zip$estimate,
        title = paste0("Oakland Income Breakdown: <br>", toString(input$target_income))
        )
    })
})
```

Row
-------------------------------------

### Plotting Covid Case rate

```{r}
covid_pal <- colorNumeric(
  palette = "Reds",
  domain =
    covidData_oakland$CaseRates
)

leaflet() %>%
        addProviderTiles(providers$Stamen.TonerLite) %>%
        addPolygons(data = covidData_oakland, stroke = TRUE, color = "black", weight = 1, smoothFactor = 0.3,
                    fillOpacity = .7,
                    fillColor = ~covid_pal(covidData_oakland_drop_geo[,2]),
                    highlight = highlightOptions(weight = 5, fillOpacity = 1.0, bringToFront =TRUE),
                    label = paste("Case Rates", covidData_oakland_drop_geo[,2], sep = ": ")) %>%
        addLegend(data = covidData_oakland_drop_geo, title = "Case Rates", pal = covid_pal,
                  values = covidData_oakland_drop_geo[,2])

```



### Plotting Covid Test Rate
```{r}
covid_pal <- colorNumeric(
  palette = "Reds",
  domain =
    covidData_oakland$TestRates
)

leaflet() %>%
        addProviderTiles(providers$Stamen.TonerLite) %>%
        addPolygons(data = covidData_oakland, stroke = TRUE, color = "black", weight = 1, smoothFactor = 0.3,
                    fillOpacity = .7,
                    fillColor = ~covid_pal(covidData_oakland_drop_geo[,3]),
                    highlight = highlightOptions(weight = 5, fillOpacity = 1.0, bringToFront =TRUE),
                    label = paste("Test Rates", covidData_oakland_drop_geo[,3], sep = ": ")) %>%
        addLegend(data = covidData_oakland_drop_geo, title = "Test Rates", pal = covid_pal,
                  values = covidData_oakland_drop_geo[,3])

```

Row
-------------------------------------

### Linear Regression to compare resulting covid case and test rate to other factors

```{r, context = "server"}
observeEvent({
  input$regression_var1
  input$regression_var2
},  {
  #if (input$regression_var1 %in% c("CaseRates", "TestRates")) {
    # alameda_grouping_by_zip <-
    #   alameda_data %>%
    #   group_by(Zip_Number, input$regression_var1, input$regression_var2) %>%
    #   summarize(estimate = sum(estimate))  %>%
    #   filter(!(Zip_Number %in% c(94720, 95377, 94621, 94603, 94613)))
    
    covid_data_plot <- ggplot(data = alameda_data,
                            aes(
                              x = input$regression_var1,
                              y = input$regression_var2
                            ))  +
     geom_point() 
    #+
  #   geom_smooth(method = "lm") +
  #   labs(
  #     x = toString(input$regression_var1),
  #     y = toString(input$regression_var2),
  #     title = paste0(
  #       " Alameda County Linear Regression of ",
  #       toString(input$regression_var1)," and ", toString(input$regression_var2))
  # )
  #   
  # 
  # } else {
  #   if(input$regression_var1 %in% c(
  #     "Less than $10,000",
  #     "$10,000 to $14,999",
  #     "$15,000 to $19,999",
  #     "$20,000 to $24,999",
  #     "$25,000 to $29,999",
  #     "$30,000 to $34,999",
  #     "$35,000 to $39,999",
  #     "$40,000 to $44,999",
  #     "$45,000 to $49,999",
  #     "$50,000 to $59,999",
  #     "$60,000 to $74,999",
  #     "$75,000 to $99,999",
  #     "$100,000 to $124,999",
  #     "$125,000 to $149,999",
  #     "$150,000 to $199,999",
  #     "$200,000 or more"
  #   )) {
  #     alameda_grouping_by_zip <-
  #       alameda_data %>%
  #       group_by(Zip_Number, income, input$regression_var2) %>%
  #       summarize(estimate = sum(estimate))  %>%
  #       filter(income == input$regression_var1) %>%
  #       filter(!(Zip_Number %in% c(94720, 95377, 94621, 94603, 94613)))
  # 
  #     covid_data_plot <- ggplot(data = alameda_grouping_by_zip,
  #                               aes(x = estimate,
  #                                   y = input$regression_var2)) +
  #       geom_point() +
  #       geom_smooth(method = "lm") +
  #       labs(
  #         x = toString(input$regression_var1),
  #         y = toString(input$regression_var2),
  #         title = paste0(
  #           " Alameda County Linear Regression of ",
  #           toString(input$regression_var1),
  #           " and ",
  #           toString(input$regression_var2)
  #         )
  #       )
  # 
  # 
  # 
  #   }else{
  #      alameda_grouping_by_zip <-
  #       alameda_data %>%
  #       group_by(Zip_Number, race, input$regression_var2) %>%
  #       summarize(estimate = sum(estimate))  %>%
  #       filter(race == input$regression_var1) %>%
  #       filter(!(Zip_Number %in% c(94720, 95377, 94621, 94603, 94613)))
  # 
  #     covid_data_plot <- ggplot(data = alameda_grouping_by_zip,
  #                               aes(x = estimate,
  #                                   y = input$regression_var2)) +
  #       geom_point() +
  #       geom_smooth(method = "lm") +
  #       labs(
  #         x = toString(input$regression_var1),
  #         y = toString(input$regression_var2),
  #         title = paste0(
  #           " Alameda County Linear Regression of ",
  #           toString(input$regression_var1),
  #           " and ",
  #           toString(input$regression_var2)
  #         )
  #       )
  # 
  #   }
  # 
  # }
  
     
    
   
})
```




### model summary

```{r, context = "server"}
#  observeEvent({
#    input$regression_var1
#    input$regression_var2
#  },  {
#    if (input$regression_var1 %in% c("CaseRates", "TestRates")) {
#  model <- lm(input$regression_var2 ~ input$regression_var1, alameda_grouping_by_zip)
#  output$sum <- renderPrint({summary(model)})
#    } else{
# 
#    }
# 
# 
# })
```

